# -*- coding: utf-8 -*-
"""AGENTES DE IA CON LANGCHAIN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LOXkYqErLyEf7PD8XlvspJFiDLshke7h
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U langchain
# %pip install -U langgraph
# %pip install -U google-generativeai
# %pip install -U langchain-google-genai
# %pip install -U langchain-community
!pip install arxiv==4.0.0 --force-reinstall --no-deps --quiet

import os
import google.generativeai as genai
from google.colab import userdata

#creamos la variable de entorno
api_key = userdata.get("GEMINI_API_KEY")
os.environ["GOOGLE_API_KEY"]=api_key
genai.configure(api_key=api_key)

#crear la instancia de gemini 2.5
#la siguiente libreria permite coneccion con genai en formato langchain
from langchain_google_genai import ChatGoogleGenerativeAI

#se declara que modelo queremos
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")

#PROMT template
#que se use la IA para analizar un area especifica
from langchain_core.prompts import PromptTemplate

#se crea el promt con el modulo que se importo, y se define la variable input_variables como tema
modelo_de_prompt = PromptTemplate(
    template="Explica de manera clara y actualizada cuáles son los impactos de la inteligencia artificial en el área de {tema}.",
    input_variables=["tema"],
)

#se importa libreria para solo obtener el texto de nuestro objeto de respuesta de la IA
from langchain_core.output_parsers import StrOutputParser

#se hace el lang chain con el siguiente flujo: 1-se da el promt, 2-se para a la llm, 3-la respuesta de llm se procesa con el modulo que extrae solo el texto
cadena = modelo_de_prompt | llm | StrOutputParser()

#se activa e imprime el resultado final del langchain
#notar que aqui se da parte del input, deficinedo el tema mediante un
#diccionario donde la clave de tema es el valor es el tema especifico a analizar
respuesta = cadena.invoke({"tema": "educación"})
print(respuesta)

"""CONECTAR TAVILY PARA HACER REQUEST EN INTERNET"""

#libreria para hacer uso de tavily, permite invocar esta herramienta
from langchain_community.tools.tavily_search import TavilySearchResults
#libreria para decorar o transformar tavily, para que se pueda usar con la IA
from langchain_core.tools import tool
import os

#accediendo a esta variable de entorno
os.environ["TAVILY_API_KEY"] = userdata.get("tavily")

#se creara una funcion pero no es normal, el @tool indica conversion de funcion para un objeto
@tool
#la declaracion de la funcion recibe como argumento una cadena de texto con el termino de busqueda
#la flecha -> list indica que la respuesta sera una lista (esta lista tendra links y resumenes)
def busca_web(query: str) -> list:
  """Realiza una búsqueda en la web sobre un tema específico"""

#en las siguientes lines se defines caracteristicas o atributos  de la busqueda
  tavily_search = TavilySearchResults(
      max_results=2, #cantidad de respuestas
      search_depth="advanced", #busqueda con mayor profundidad
      max_tokens=1000 #cuanto texto puede devolver como resultado
  )
  resultado_busca = tavily_search.invoke(query) #se invoca la respuesta
  return resultado_busca

#Vamos a probar la herramienta, pero como no es una funcion normal la @tool
#se tiene que llamra de manera diferente, por eso se usa el invoke
busca_web.invoke("impacto de la inteligencia artificial en la educación")

"""AHORA SE CONECTARA CON GEMINI
notar que casi se uso el mismo codigo usado al inicio para el request de la educacion
"""

#esta variable tiene la capacidad de hacer lo que hicimos para consulta de web
tools = [busca_web]

#esto le dice a gemini que herramientas puede usar
llm_con_herramienta = llm.bind(tools=tools)

from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

#aqui cambia el promt, ya que se dice que responda la pregunta pero solo con las herramientas

modelo_de_prompt = PromptTemplate(
    template="Usando solo las tools disponibles, dime cuáles son los impactos de la inteligencia artificial en el área de {tema}.",
    input_variables=["tema"],
)

cadena = modelo_de_prompt | llm_con_herramienta | StrOutputParser()

#se invoca o activa el flujo
respuesta =  cadena.invoke({"tema": "educación"})

#hasta aqui hay una respuesta vacia, si identifica que herramienta y que tema
#pero no da respuesta
respuesta

prompt = "Usando solo las tools disponibles, dime cuáles son los impactos de la inteligencia artificial en el área de {tema}."

respuesta = llm_con_herramienta.invoke(prompt)

print(respuesta)

"""Se observa que la respuesta final no esta completa, se menciona que para eso se necesita un ciclo de razonamiento"""

#importamos al agente preconfigurado de ReAct
from langgraph.prebuilt import create_react_agent

#definimos el promt para darle las instruciones al agente react
#notar que le dijismos que use la herramienta busca web que generamos en este codigo
system_prompt = """
Actúa como un asistente útil y especializado en investigación.
Utiliza las herramientas proporcionadas para responder a las preguntas del usuario.

Herramientas disponibles:
- busca_web: realiza búsquedas en la web y devuelve enlaces y resúmenes.

Siempre que el usuario pregunte sobre un tema específico:
1. Usa la herramienta busca_web.
2. Analiza los resultados.
3. Devuelve una respuesta clara.
4. Incluye los enlaces de las fuentes utilizadas.
"""

agente_web = create_react_agent( #en esta linea se pone el modulo que importamos para agentes preconf
    model=llm, #asi se declara la llm de gemini
    tools=tools, #aqui es donde declaramos nuestras tools que estan contenidas en la funcion "busca_web"
    prompt=system_prompt #se declara el promt que recibira
)

#Ahora le pasamos un mensaje al agente
#notar que el input sigue el mismo formato que hemos venido trabajando con gemini
#solo que agente_web.invoke tiene todo lo configurado acerca de promt, criterio, agente preconf react, etc
resultado = agente_web.invoke({
    "messages": [
        ("user", "Cuáles son los impactos de la inteligencia artificial en la educación?")
    ]
})

#se llama al resultado, el cual se ve un objeto con muchas variables
#una salida completa
resultado

#obtener una respuesta mas limpia
#esto imprime unicamente el ultimo mensaje o respuesta dada por la IA
resultado["messages"][-1]

"""Inicio de integracion de otro agente que busca info de articulos cientificos"""

#libreria que permite accesar a articulos cientificos
#from langchain_community.tools.arxiv.tool import ArxivQueryRun

#se crea una variable que es igual al modulo para el acceso a articulo
#tool_cientifica = ArxivQueryRun()

"""
#ESTAS LINEAS DE CODIGO FALLARON YA QUE LA FORMA DE INSTALAR LA
LIBRERIA QUE NOS COMPARTIO EL INSTRUCTOR (%pip install arxiv) INSTALABA UNA VERSION VIEJA
LUEGO SE CAMBIO LA FORMA DE INSTALACION POR !pip install arxiv==4.0.0 --force-reinstall --no-deps --quiet
PARA FORZAR LA INSTALACION DE LA NUEVA VERSION (MANERA EN QUE ESTA EN ESTE CODIGO)
PERO TAMPOCO FUNCIONABA YA QUE LA VERSION ACTUAL NO ERA COMPATIBLE CON NUESTRO REQUEST

POR ESO SE HIZO LA SIGUIENTE LINEA DE CODIGO, LA CUAL ES MUY OARECIDA A LA QUE SE HIZO PARA EL USO
DE LA LIBRERIA TAVILY. SE OBSERVA QUE LA SINTAXIS RESPECTO A LA TOOL DE TAILVY
ES MUY PARECIDA A LA DE ArxivQueryRun(), ESE FUE EL OBJETIVO LOGRAR UN OUTPUT
PARECIDO A ESE MODULO, PERO DEFINIENDO NOSOTROS LOS CRITERIOS PARA PODER HACER USO DE LA ULTIMA
VERSION DE ARXIV

"""

import arxiv

@tool
def busca_arxiv(query: str) -> str:
    """Busca artículos científicos en arXiv sobre un tema específico y devuelve sus títulos y resúmenes."""
    client = arxiv.Client()
    search = arxiv.Search(
        query=query,
        max_results=3,
        sort_by=arxiv.SortCriterion.Relevance
    )
    resultados = []
    for paper in client.results(search):
        resultados.append(f"Título: {paper.title}\nResumen: {paper.summary[:300]}...\nURL: {paper.entry_id}")
    return "\n\n".join(resultados) if resultados else "No se encontraron resultados."

tool_cientifica = busca_arxiv

#se declara un nuevo system promt ya que sera otro agente
#esta es una guia para su comportamiento
system_prompt2 = """
Actúa como un asistente útil.
Usa las herramientas proporcionadas para responder a las preguntas del usuario.

- tool_cientifica: Retorna resultados de una búsqueda en arXiv.

Cuando el usuario pregunte sobre un tema específico, usa tool_cientifica y devuelve los títulos de los artículos.
"""

#definimos los parametros para este nuevo agente \
agente_cientifico = create_react_agent(
    model=llm,
    tools=[tool_cientifica],
    prompt=system_prompt2
)

import importlib.metadata
print(importlib.metadata.version("arxiv"))

#le damos el input en formato que pide gemini
#notar que el mensaje o request se puso en ingles
#ya que es modulo arxive funciona mejor en este idioma
resultado = agente_cientifico.invoke({
    "messages": [
        ("user", "AI impact in education")
    ]
})

resultado

"""Ahora haremos una estrutura de comunicacion entre resultado busqueda web y articulo cientifico"""

from typing import TypedDict

#clase para combinar respuestas de agentes
#recibe como argumento el modulo typedDict
class AgentState(TypedDict):
    #se definen los formatos de entrada y salida
    user_query: str
    web_answer: str
    scientific_answer: str
    final_answer: str

#funciones que encapsulan la respuesta del agente web y otra para cientifico

#primero se hara la que encapsula al agente web
#en la primera linea se ve que se generara una lista con datos estructurados tipo JSON
def funcion_agente_web(state: AgentState) -> dict:
    #definir comportamiento del agente
    """
    Función que ejecuta un agente al estilo ReAct que realiza una búsqueda en la web
    sobre un término específico.

    Esta funcion toma el estado actual del agente (que contiene la pregunta del usuario)
    y crea un agente utilizando Gemini y la herramienta Tailvy, y retorna la respuesta del agente.

    Arg:
        state (AgentState): Un diccionario que contiene la pregunta del usuario y la
        respuesta del agente

    Returns:
        dict: la respuesta del agente.
    """

    #a partir de aqui se pone lo mismo que cuando se comenzo a configurar el agente busca_web
    #el siguiente promt puede ser el mismo que se uso en la parte donde se llama el aegnte_web
    system_prompt = """
    Actúa como un asistente útil.
    Usa las herramientas proporcionadas para responder a las preguntas del usuario.

    - busca_web: Retorna resultados de búsqueda web.

    Cuando el usuario pregunte sobre un tema específico, usa busca_web y devuelve enlaces en la respuesta.
    """
    #se le dan criterios al agente los mismos que habiamos puesto
    agente_web = create_react_agent(
        model=llm,
        tools=tools,
        prompt=system_prompt
    )

    #notar que en esta parte que se corre al agente, ahora el input o el request no es un texto explicito
    #ahora se espera que el usuario lo introduzca
    resultado = agente_web.invoke({
        "messages": [("user", state["user_query"])]
    })

    #se le da formato a la respuesta final, igual que antes slicing de values de "messages"
    respuesta_final = resultado["messages"][-1].content
    if isinstance(respuesta_final, list):
      respuesta_final = respuesta_final[0]["text"]
    #aqui se dice que la salida sera un diccionario con su key web_ansswer y el value la respuesta final
    return {"web_answer": respuesta_final}

#ahora se hara la que encapsula al agente cientifico
def funcion_agente_cientifico(state: AgentState) -> dict:
    #notar que en los promts cambia Tailvy por Arxiv
    """
    Función que ejecuta un agente al estilo ReAct que realiza una búsqueda en arXiv
    sobre un término específico.

    Esta funcion toma el estado actual del agente (que contiene la pregunta del usuario)
    y crea un agente utilizando Gemini y la herramienta arXiv, y retorna la respuesta del agente.

    Arg:
        state (AgentState): Un diccionario que contiene la pregunta del usuario y la
        respuesta del agente

    Returns:
        dict: la respuesta del agente.
    """

    #A partir de aqui es lo mismo de antes, solo dando las especificaciones para que use la
    #tool de agente_cientifico
    system_prompt = """
    Actúa como un asistente útil.
    Usa las herramientas proporcionadas para responder a las preguntas del usuario.

    - tool_cientifica: Retorna resultados de una búsqueda en arXiv.

    Cuando el usuario pregunte sobre un tema específico, usa tool_cientifica y devuelve los títulos de los artículos.
    """


    agente_cientifico = create_react_agent(
        model=llm,
        tools=[tool_cientifica], #aqui se llama la tool cientifica
        prompt=system_prompt
    )

    resultado = agente_cientifico.invoke({
        "messages": [("user", state["user_query"])]
    })

    #aqui el key del diciconario cambia a scientific answer en lugar de web answer
    respuesta_final = resultado["messages"][-1].content
    if isinstance(respuesta_final, list):
      respuesta_final = respuesta_final[0]["text"]
    return {"scientific_answer": respuesta_final}

"""ORQUESTANDO LOS AGENTES CON LANGGRAPH PARA COMBINAR RESPUESTAS DE AGENTES"""

#se importan tres modulos
#START Y END marcan inicio y final de este flujo
from langgraph.graph import START, StateGraph, END

#se iniciara con flujo basico con un solo agente
workflow = StateGraph(AgentState)

#se ponen nodos (se anaden pasos al grapo) y edge (definicio de flujo entre pasos)

#primero nodo que contiene la funcion
workflow.add_node("agente_web", funcion_agente_web)
#Se indica que se inicia el flujo
workflow.add_edge(START, "agente_web")
#se indica donde termina el flujo
workflow.add_edge("agente_web", END)

#compilacion del workflow
app = workflow.compile()

"""Se hara funcion para tener un flujo visual"""

from IPython.display import Image, display

#se toma el grapho en forma de imagen y se dibuja diagrama con ejecusion
Image(app.get_graph().draw_mermaid_png())

#ahora se activa el flujo con invoke y se define el request, impacto de IA en medicina
resultado = app.invoke({"user_query": "Cuál es el impacto de la IA en la medicina"})

print(resultado["web_answer"])

"""Nodo supervisor para combinar respuestar"""

def supervisor_node(state: AgentState) -> dict:
  #se inicia por dar info de como comportarse
  #este se puede ver como agente que revisa y combina la respuesta final
  """
  Combina los resultados de los agentes web y cientificos y formatea la respuesta final.

  Args:
    state (AgentState): El estado actual del agente, que contiene web_answer y scientific_answer.
  Returns:
    dict: Un diccionario que contiene la respuesta final combinada y formateada.
  """

  #Ahora se hace definicion por si algo no sale bien el codigo
  web_results = str(state.get("web_answer", "No se realizó búsqueda web."))
  #              0                 1                     2
  #0 convierte la salida en str, 1 se corre si no hubo error, el 2 se activa si hubo error
  scientific_results = str(state.get("scientific_answer", "No se realizó búsqueda científica."))

  #formatacion de respuesta final
  final_answer = '## Resultados combinados de búsqueda\n\n' #primero se imprime este str
  final_answer += '### Resultados desde la Web\n\n' + web_results + '\n\n' #se anade esto
  final_answer += '### Artículos científicos (arXiv)\n\n' + scientific_results #luego esto

  return {"final_answer": final_answer}

"""Se crea ahora si un flujo para los dos agentes y luego se llamra a esta funcion que los combina a los dos"""

#inciando por la creacion del flujo
workflow = StateGraph(AgentState)

#aqui se ve como se define un flow con varios agentes
#primero se definen los nombres con sus respectivas funciones
workflow.add_node("web_search", funcion_agente_web)
workflow.add_node("scientific_search", funcion_agente_cientifico)
workflow.add_node("supervisor", supervisor_node)

#aqui se define el flujo como tal, donde inicia y donde termina
workflow.add_edge(START, "web_search")
workflow.add_edge("web_search", "scientific_search")
workflow.add_edge("scientific_search", "supervisor")
workflow.add_edge("supervisor", END)

#se hace la compilacion
app = workflow.compile()

#Crear la nueva demostracion visual con este nuevo flujo
Image(app.get_graph().draw_mermaid_png())

#Ahora si se activa el flujo, dando el request y se imprime la respuesta
resultado = app.invoke({"user_query": "Cuál el impacto de la IA en la medicina?"})
print(resultado["final_answer"])

"""Implementacion de router para eleccion de agente segun la pregunta"""

def router_agent(state: AgentState) -> dict:
  #al igual que los otros agentes se da un promt para que sepa su funcionamiento
  router_prompt = """
  Eres un agente ruteador. Tu tarea es decidir cuál agente es más apropiado
  para responder la pregunta del usuario.

  Pregunta del usuario: {user_query}

  Puedes elegir entre las siguientes opciones:
  - web_search: Usa esta opción si la pregunta requiere una búsqueda general en internet.
  - scientific_search: Usa esta opción si la pregunta requiere artículos científicos.

  Responde ÚNICAMENTE con el nombre de la opción (web_search o scientific_search).
  """

  #se crea el agente con sus caracteristicas
  router_agent_instance = create_react_agent(
      model=llm,
      tools=[], #Notar que las tools estan vacias porque este agente no necesita herramienta externa, razona con el puro texto
      prompt=router_prompt
  )

  #Se invoca la llm con el agente creado
  response = router_agent_instance.invoke({
      "messages": [("user", state["user_query"])]
  })

  #se crea variable que contiene solo la parte del mensaje que nos interesa, con formactacion de texto
  decision = response["messages"][-1].content.strip().lower()

  #se retorna el resultado basado en contenido
  #como este agente responde con web_search o scientific_search
  #la respuesta de este agente regresa el diccionario con key "router_decision" y value la decision
  if decision == "web_search":
      return {"router_decision": "web_search"}
  elif decision == "scientific_search":
      return {"router_decision": "scientific_search"}

  # Por defecto, usamos web_search
  return {"router_decision": "web_search"}

#crear un nuevo workflow
workflow = StateGraph(AgentState)

#definir los nodos
workflow.add_node("router", router_agent)
workflow.add_node("web_search", funcion_agente_web)
workflow.add_node("scientific_search", funcion_agente_cientifico)
workflow.add_node("supervisor", supervisor_node)

#se define el punto de inicio del flujo y el router condicional
workflow.add_edge(START, "router") #indica inicio de flujo
workflow.add_conditional_edges( #notar que en lugar de edge es conditional para agregar un nodo condicional
    "router",
    lambda state: state["router_decision"],
    {
        "web_search": "web_search",
        "scientific_search": "scientific_search",
    }
)
#aqui cambia el flujo tmn, ya no se indica que cuando termina un agente inicie el otro, mas bien se indica
#que si el valor es "web_search" o "scientific_search" directo a supervisor
#y una vez activado el supervisor se termina
workflow.add_edge("web_search", "supervisor")
workflow.add_edge("scientific_search", "supervisor")
workflow.add_edge("supervisor", END)

#compilacion de flujo
app = workflow.compile()

#visualizacion de grapho
Image(app.get_graph().draw_mermaid_png())

#Prueba con info de web
resultado = app.invoke({
    "user_query": "Cuál es el impacto de la IA en la Educación? Usa solo fuentes web"
})
print(resultado["final_answer"])

#Prueba con info cientifica
resultado = app.invoke({
    "user_query": "Cuál es el impacto de la IA en la Educación? Usa solo fuentes cientificas"
})

print(resultado["final_answer"])

"""SE HARA UNA INTERFAZ LIMPIA E INTERACTIVA"""

import gradio as gr

#Se crea la funcion que encapsula toda la logica del grapho
#lo que reciebe esta funcion es el user query
def run_graph(user_query):
  #se le da elt promt
  """Ejecuta el LangGraph con la pregunta del usuario y devulve la respuesta final."""

  #se activa todo el grapho con app.invoke
  result = app.invoke({"user_query": user_query}) #notar que en la varibale app esta todos los agentes, flujos, etc
  return result["final_answer"]

  #ESTA FUNCION ES LA RESPONSABLE DE ALIMENTAR A LA INTERFAZ

#SE CONSTRUYE LA INTERFAZ
iface = gr.Interface(
    fn=run_graph, #funcion que se usara
    inputs=gr.Textbox(label="Escribe tu pregunta:"), #se pide la pregunta del usuario (caja de texto)
    outputs=gr.Markdown(label="Respuesta final"), #se da etiqueta a respuesta final
    title="Agente de Búsqueda Inteligente" ,
    description="Haz una pregunta y obtén una respuesta usando fuentes web o científicas."
)

#se llama o activa el visualizador
iface.launch()
